#! /bin/sh

set -e

source /etc/portage/make.conf

: ${PORTAGE_NICENESS?=0}

if [ -n "${MAKEOPTS}" ]
then
	export MAKEOPTS
fi

LINUX_BUILD='/var/tmp/portage/linux'
LINUX_CFG="${LINUX_BUILD}/.config"

if [ ! -e "${LINUX_BUILD}" ]
then
	echo Creating build directory
	mkdir -p "${LINUX_BUILD}"
fi

if [ ! -e "${LINUX_CFG}" ]
then
	echo Extracting configuration from running kernel
	zcat "/proc/config.gz" > "${LINUX_CFG}"
fi

function call_linux_make() {
	nice -n ${PORTAGE_NICENESS} make O="${LINUX_BUILD}" "${@}"
}

if [ ! -e "${LINUX_CFG}.old" ]
then
	echo Regenerating configuration
	call_linux_make oldconfig
fi

case "${1}"
in
	build) call_linux_make ;;
	*) call_linux_make "${@}" ;;
esac
