#! /bin/sh

set -e

source /etc/portage/make.conf

: ${PORTAGE_NICENESS?=0}

LINUX_BUILD='/var/tmp/portage/linux'
LINUX_CFG="${LINUX_BUILD}/.config"

if [ -n "${INSTALL_PATH}" ]
then
	echo "Kernel will be installed to: ${INSTALL_PATH}"
	export INSTALL_PATH
fi

function get_src() {
	echo /usr/src/linux-* \
	| xargs -n1 \
	| sort -rV \
	| head -n1
}

SRC_DIR="$(get_src)"
cd "${SRC_DIR}"

if [ ! -e "${LINUX_BUILD}" ]
then
	echo Creating build directory
	mkdir -p "${LINUX_BUILD}"
fi

if [ ! -e "${LINUX_CFG}" ]
then
	echo Extracting configuration from running kernel
	zcat "/proc/config.gz" > "${LINUX_CFG}"
fi

function call_linux_make() {
	nice -n ${PORTAGE_NICENESS} make ${MAKEOPTS} O="${LINUX_BUILD}" "${@}"
}

if [ ! -e "${LINUX_CFG}.old" ]
then
	echo Regenerating configuration
	call_linux_make oldconfig
fi

case "${1}"
in
	build) call_linux_make ;;
	*) call_linux_make "${@}" ;;
esac
