#! /bin/sh

BASE='https://www.youtube.com'
SEARCH="${BASE}/results?search_query="
if [ "${1}x" = '-vx' ]
then
	shift
	ARGS=''
else
	ARGS='--no-vid'
fi

function get_video_links() {
	curl "${SEARCH}$(echo $@ | sed 's/ /+/g')" \
	| grep -o '/watch?v=[^"]\+' \
	| sed "s#.*#${BASE}&#"
}

exec mpv ${ARGS} $(get_video_links "${@}")
