#! /bin/sh

CONFIG="/etc/s6rcupdate.conf"

if [ -r "${CONFIG}" ]
then
	source "${CONFIG}"
fi

TS=$(date +%s)
RC_PATH="/etc/s6-rc"
COMPIELD="${RC_PATH}/compiled"
COMPIELD_NEW="${COMPIELD}${TS}"
SRC=(
	"${RC_PATH}/source/$(hostname)/"*
)

: ${S6_RC_SRC:=${SRC[@]}}

function die () {
	echo "$@" >&2
	exit 1
}

echo "Compiling ${S6_RC_SRC[@]} to ${COMPIELD_NEW}"
s6-rc-compile "${COMPIELD_NEW}" ${S6_RC_SRC[@]} \
|| die "Cannot compile ${S6_RC_SRC[@]}"

if [ -e "${COMPIELD}" ]
then
	echo "Update db from ${COMPIELD_NEW}"
	s6-rc-update "${COMPIELD_NEW}" \
	|| die "Cannot update new db ${COMPIELD_NEW}"
fi

echo "Switching symlink"
ln -snf "${COMPIELD_NEW}" "${COMPIELD}" \
|| die "Cannot update the symlink"
